# Generated by Django 4.2.5 on 2023-09-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='имя пользователя')),
                ('fullname', models.CharField(max_length=150, verbose_name='ФИ0')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='почта')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='номер телефона')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='аватарка')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
