# Generated by Django 4.2.6 on 2023-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_group_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
