# Generated by Django 4.2.6 on 2023-10-23 17:03

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=150, verbose_name='последнее посещение'),
            preserve_default=False,
        ),
    ]
