# Generated by Django 4.2.5 on 2023-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_course_options_alter_lesson_options_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=20, verbose_name='способ оплаты'),
        ),
    ]
