# Generated by Django 4.2.5 on 2023-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.CharField(verbose_name='дата оплаты'),
        ),
    ]
