# Generated by Django 4.2.6 on 2023-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_lesson_course_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModeratorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Группа модераторов',
                'verbose_name_plural': 'Группы модераторов',
            },
        ),
    ]
